---
# make sure ports are open on FW
#- firewalld: port=2181/tcp permanent=true state=enabled
#- firewalld: port=2888/tcp permanent=true state=enabled
#- firewalld: port=3888/tcp permanent=true state=enabled

- name: Restart zookeeper
  service: name=zookeeper state=restarted
